from model.academic_department import AcademicDepartment
from model.defense import Defense
from model.defense_committee import DefenseCommittee
from model.defense_committee_members import DefenseCommitteeMembers
from model.defense_localization import DefenseLocalization
from model.degree import Degree
from model.faculty import Faculty
from model.keywords import Keywords
from model.researchers import Researchers
from model.review import Review
from model.students import Students
from model.studies_type import StudiesType
from model.theses import Theses
from model.theses_authors import ThesesAuthors
from model.theses_keywords import ThesesKeywords
from model.university_course import UniversityCourse
